import { useState } from "react";
import { ChecklistItem } from "./ChecklistItem";
import { ChecklistScore } from "./ChecklistScore";
import { useChecklist } from "./ChecklistContext";
import { Button } from "@/components/ui/button";
import { Download, Mail, RotateCcw, ChevronDown, ChevronUp } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { trackEvent } from "@/hooks/usePageTracking";
import jsPDF from "jspdf";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";

export interface ChecklistItemData {
  id: string;
  label: string;
  description?: string;
  helpText?: string;
}

export interface ChecklistCategory {
  id: string;
  title: string;
  description?: string;
  items: ChecklistItemData[];
}

interface InteractiveChecklistProps {
  checklistId: string;
  title: string;
  description?: string;
  categories: ChecklistCategory[];
  onComplete?: (score: number) => void;
  showEmailCapture?: boolean;
}

export const InteractiveChecklist = ({
  checklistId,
  title,
  description,
  categories,
  onComplete,
  showEmailCapture = true
}: InteractiveChecklistProps) => {
  const { checklistState, toggleItem, resetChecklist, getProgress } = useChecklist();
  const [openCategories, setOpenCategories] = useState<Set<string>>(new Set(categories.map(c => c.id)));

  const totalItems = categories.reduce((sum, cat) => sum + cat.items.length, 0);
  const progress = getProgress(checklistId, totalItems);

  const toggleCategory = (categoryId: string) => {
    setOpenCategories(prev => {
      const next = new Set(prev);
      if (next.has(categoryId)) {
        next.delete(categoryId);
      } else {
        next.add(categoryId);
      }
      return next;
    });
  };

  const handleReset = () => {
    resetChecklist(checklistId);
    toast.success("Checklist reset successfully");
    trackEvent("checklist_reset", { checklistId });
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPosition = margin;

    // Header
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Score: ${progress}% Complete`, margin, yPosition);
    yPosition += 15;

    // Categories
    categories.forEach(category => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = margin;
      }

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text(category.title, margin, yPosition);
      yPosition += 8;

      category.items.forEach(item => {
        const isChecked = checklistState[checklistId]?.[item.id] || false;
        const checkbox = isChecked ? "[X]" : "[ ]";
        
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.text(`${checkbox} ${item.label}`, margin + 5, yPosition);
        yPosition += 6;

        if (yPosition > 270) {
          doc.addPage();
          yPosition = margin;
        }
      });

      yPosition += 5;
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setFont("helvetica", "italic");
      doc.text("Generated by CWT Studio", margin, doc.internal.pageSize.getHeight() - 10);
    }

    doc.save(`${checklistId}-results.pdf`);
    toast.success("PDF downloaded successfully");
    trackEvent("checklist_pdf_download", { checklistId, score: progress });
  };

  const handleEmailCapture = () => {
    toast.info("Email capture feature coming soon");
    trackEvent("checklist_email_intent", { checklistId, score: progress });
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="space-y-4">
        <div>
          <h2 className="heading-section mb-2">{title}</h2>
          {description && (
            <p className="text-muted-foreground">{description}</p>
          )}
        </div>

        {/* Score */}
        <ChecklistScore score={progress} category={title} />

        {/* Actions */}
        <div className="flex flex-wrap gap-3">
          <Button onClick={generatePDF} variant="outline" size="sm">
            <Download className="w-4 h-4 mr-2" />
            Export PDF
          </Button>
          {showEmailCapture && (
            <Button onClick={handleEmailCapture} variant="outline" size="sm">
              <Mail className="w-4 h-4 mr-2" />
              Email Results
            </Button>
          )}
          <Button onClick={handleReset} variant="ghost" size="sm">
            <RotateCcw className="w-4 h-4 mr-2" />
            Reset
          </Button>
        </div>
      </div>

      {/* Categories */}
      <div className="space-y-4">
        {categories.map((category) => {
          const categoryItems = category.items.length;
          const categoryCompleted = category.items.filter(
            item => checklistState[checklistId]?.[item.id]
          ).length;
          const categoryProgress = categoryItems > 0 
            ? Math.round((categoryCompleted / categoryItems) * 100) 
            : 0;
          const isOpen = openCategories.has(category.id);

          return (
            <Collapsible key={category.id} open={isOpen} onOpenChange={() => toggleCategory(category.id)}>
              <div className="border border-border rounded-lg overflow-hidden">
                <CollapsibleTrigger className="w-full p-6 flex items-center justify-between hover:bg-muted/50 transition-colors">
                  <div className="flex-1 text-left space-y-2">
                    <div className="flex items-center gap-4">
                      <h3 className="font-mono font-bold text-lg">{category.title}</h3>
                      <span className="text-xs font-mono text-muted-foreground">
                        {categoryCompleted}/{categoryItems}
                      </span>
                    </div>
                    {category.description && (
                      <p className="text-sm text-muted-foreground">{category.description}</p>
                    )}
                    <div className="h-1.5 bg-muted rounded-full overflow-hidden max-w-xs">
                      <div
                        className="h-full bg-primary transition-all duration-300"
                        style={{ width: `${categoryProgress}%` }}
                      />
                    </div>
                  </div>
                  {isOpen ? (
                    <ChevronUp className="w-5 h-5 text-muted-foreground" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-muted-foreground" />
                  )}
                </CollapsibleTrigger>

                <CollapsibleContent>
                  <div className="p-6 pt-0 space-y-3">
                    {category.items.map((item) => (
                  <ChecklistItem
                    key={item.id}
                    id={item.id}
                    label={item.label}
                    description={item.description}
                    helpText={item.helpText}
                    checked={(checklistState[checklistId]?.[item.id] === "yes") || false}
                    onChange={() => {
                      toggleItem(checklistId, item.id);
                          trackEvent("checklist_item_toggle", { 
                            checklistId, 
                            itemId: item.id,
                            categoryId: category.id
                          });
                        }}
                      />
                    ))}
                  </div>
                </CollapsibleContent>
              </div>
            </Collapsible>
          );
        })}
      </div>
    </div>
  );
};
